// Planes de estudio de Posgrado tal como figuran en el tablero de contratación:
// carrera, código, nombre, orden en el plan, estado de origen, docente, asesor.
// Es el catálogo completo — no todas tienen período asignado, y de eso se trata
// justamente el planificador.
export type FilaPlan = [carrera: string, codigo: string, nombre: string, orden: number, estado: string, docente: string, asesor: string]

export const PLANES_POSGRADO: FilaPlan[] = [
  ['Cooperación Internacional', 'EP02430', 'AGENDAS GLOBALES Y COOPERACIÓN INTERNACIONAL', 1, '5.FINALIZADA', 'Viviana Arias', 'Lucia Moro'],
  ['Cooperación Internacional', 'EP02355', 'APORTES TEÓRICO-CONCEPTUALES SOBRE COOPERACIÓN INTERNACIONAL Y DESARROLLO', 2, '5.FINALIZADA', 'Milton Escobar/ Natalia Sánchez', 'Marcelo Hangshel Pentimalli'],
  ['Cooperación Internacional', 'EP00035', 'METODOLOGÍA Y GESTIÓN DE PROYECTOS DE COOPERACIÓN', 3, '5.FINALIZADA', 'Gonzalo Andrés Mozas/ Analía Nievas', 'Lucia Moro'],
  ['Cooperación Internacional', 'EP02245', 'COOPERACIÓN SUR-SUR EN PERSPECTIVA MULTILATERAL', 4, '5.FINALIZADA', 'Viviana Arias/ Ana Ciuti', 'Marcelo Hangshel Pentimalli'],
  ['Cooperación Internacional', 'EP01819', 'GESTIÓN DE RIESGO Y COOPERACIÓN INTERNACIONAL PARA EL DESARROLLO', 5, '3.MAQUETACIÓN', 'Silvia Fontana/ Virginia Escañuela', 'Marcelo Hangshel Pentimalli'],
  ['Cooperación Internacional', 'EP01123', 'INTERNACIONALIZACIÓN DE GOBIERNOS LOCALES', 6, '5.FINALIZADA', 'Simón González', 'Agostina Cortona'],
  ['Cooperación Internacional', 'EP01575', 'ÉTICA Y COOPERACIÓN INTERNACIONAL', 7, '3.MAQUETACIÓN', 'Griselda Ibaña', 'Yamile Abed'],
  ['Cooperación Internacional', 'EP01506', 'EVALUACIÓN DE PROYECTOS DE COOPERACIÓN INTERNACIONAL', 8, '3.MAQUETACIÓN', 'Silvana Rufail', 'Yamile Abed'],
  ['Cooperación Internacional', 'EP02028', 'PLANIFICACIÓN, POLÍTICAS Y FINANCIAMIENTO INTERNACIONAL', 9, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Silvana Rufail / Sofía Garzón', 'Yamile Abed'],
  ['Cooperación Internacional', 'EP02568', 'SEMINARIOS ELECTIVOS', 10, '5.FINALIZADA', '', ''],
  ['Cooperación Internacional', 'EP02149', 'TALLER DE TRABAJO FINAL INTEGRADOR', 11, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Micaela Nancy Cerezoli y Natalia Alejandra Sánchez', 'Yamile Abed'],
  ['Cooperación Internacional', 'PLAN-12', 'TRABAJO FINAL INTEGRADOR', 12, '', '', ''],

  ['Dirección de Empresas', 'EP00878', 'REFLEXIÓN Y ANÁLISIS ESTRATÉGICO', 1, '5.FINALIZADA', 'Ana Fité - Virginia Rosales Paur', 'Marcelo Hangshel Pentimalli'],
  ['Dirección de Empresas', 'EP02618', 'ENTORNO CULTURAL, SOCIAL, POLÍTICO Y ECONÓMICO', 2, '5.FINALIZADA', 'Gisela Veritier', 'Lucía Rodriguez'],
  ['Dirección de Empresas', 'EP01180', 'GESTIÓN ESTRATÉGICA DEL TALENTO', 3, '5.FINALIZADA', 'Elena Colasanti', 'Jorgelina Rodriguez Jauregui'],
  ['Dirección de Empresas', 'EP00461', 'TALLERES DE APOYO PARA LA REALIZACIÓN DEL TRABAJO FINAL', 4, '3.MAQUETACIÓN', 'Giovanardi Mariana Alejandra', 'Anahí Azcuy'],
  ['Dirección de Empresas', 'EP01155', 'SISTEMAS DE INFORMACIÓN PARA LA CREACIÓN DE VALOR', 5, '5.FINALIZADA', 'Marcelo Hangshel Pentimalli', 'Lucía Rodriguez'],
  ['Dirección de Empresas', 'EP00046', 'ANÁLISIS ESTRATÉGICO DE LOS MERCADOS', 6, '5.FINALIZADA', 'Juan Pablo Mon', 'Evelin Pineda'],
  ['Dirección de Empresas', 'EP02397', 'HERRAMIENTAS MATEMÁTICAS', 7, '5.FINALIZADA', 'Valentina Pulcini', 'Lucía Rodriguez'],
  ['Dirección de Empresas', 'EP00128', 'HERRAMIENTAS CONTABLES', 8, '5.FINALIZADA', 'Santiago Martín', 'Jorgelina Rodriguez Jauregui'],
  ['Dirección de Empresas', 'EP00402', 'ANÁLISIS FINANCIERO PARA LA TOMA DE DECISIONES', 9, '5.FINALIZADA', 'Gabriel Feldman', 'Adriana Hermosilla'],
  ['Dirección de Empresas', 'EP02044', 'SATISFACTORES Y CANALES: EL MARKETING DE LA EXPERIENCIA DEL CLIENTE', 10, '5.FINALIZADA', 'Daniel Bordabossana', 'Florencia Palpacelli'],
  ['Dirección de Empresas', 'EP00843', 'DIRECCIÓN DE OPERACIONES ORIENTADAS AL CLIENTE', 11, '3.MAQUETACIÓN', 'Claudio Araya', 'Victoria Coria'],
  ['Dirección de Empresas', 'EP00209', 'GESTIÓN PRESUPUESTARIA Y DEL CAPITAL DE TRABAJO', 12, '5.FINALIZADA', 'Mario Perossa', 'Adriana Hermosilla'],
  ['Dirección de Empresas', 'EP02109', 'LIDERAZGO INSPIRADOR Y CREADOR DE VALOR', 13, '5.FINALIZADA', 'Jorge W. Barrientos', 'Victoria Coria'],
  ['Dirección de Empresas', 'EP00232', 'ENTORNO JURÍDICO DE LA ACTIVIDAD EMPRESARIAL', 14, '5.FINALIZADA', 'Dante Pusiol', 'Evelin Pineda'],
  ['Dirección de Empresas', 'EP00596', 'INNOVACIÓN EN MODELOS DE NEGOCIOS, SATISFACTORES Y PROCESOS', 15, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Cristian Balmaceda', 'Yamile Abed'],
  ['Dirección de Empresas', 'EP00881', 'COMUNICACIÓN INTEGRAL EN MARKETING, COMUNIDADES E INTANGIBLES', 16, '3.MAQUETACIÓN', 'Juan Carlos Olivero', 'Yamile Abed'],
  ['Dirección de Empresas', 'EP00223', 'ESTRATEGIAS DE NEGOCIOS Y DECISIONES', 17, '3.MAQUETACIÓN', 'Juan Carlos Olivero', 'Yamile Abed'],
  ['Dirección de Empresas', 'EP01864', 'SEMINARIO I', 18, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Barrientos', 'Victoria Coria'],
  ['Dirección de Empresas', 'EP01396', 'INSTRUMENTOS DEL SISTEMA FINANCIERO', 19, '3.MAQUETACIÓN', 'Sánchez, Gabriel Leandro', ''],
  ['Dirección de Empresas', 'EP00728', 'HABILIDADES Y COMPETENCIAS DIRECTIVAS', 20, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Claudia Martinez', 'Victoria Coria'],
  ['Dirección de Empresas', 'EP00971', 'EL PRICING Y EL ABORDAJE ESTRATÉGICO DE LOS MERCADOS', 21, '2.CONSTRUCCIÓN DE CONTENIDOS', 'DEsposito, Horacio', ''],
  ['Dirección de Empresas', 'EP02266', 'CADENA DE VALOR Y VENTAJAS COMPETITIVAS', 22, '2.CONSTRUCCIÓN DE CONTENIDOS', '', ''],
  ['Dirección de Empresas', 'EP00582', 'SELECCIÓN Y OPTIMIZACIÓN DE INVERSIONES', 23, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Olivo, Sergio Luis', ''],
  ['Dirección de Empresas', 'EP02114', 'SEMINARIO II', 24, '0- NO INICIADO', '', ''],
  ['Dirección de Empresas', 'EP00436', 'ÉTICA Y RESPONSABILIDAD SOCIAL EMPRESARIA', 25, '0. PROXIMAMENTE', 'Cocorda, Esteban', ''],
  ['Dirección de Empresas', 'EP02022', 'POLÍTICAS PARA LA GESTIÓN ESTRATÉGICA DEL TALENTO', 26, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Lucia Moro', 'Bordabosana'],
  ['Dirección de Empresas', 'EP00463', 'ESTRATEGIA PUESTA EN ACCIÓN: LA IMPLEMENTACIÓN', 27, '1.CONTRATACIÓN', '', ''],
  ['Dirección de Empresas', 'EP01740', 'CONTROL INTEGRADO DE LA GESTIÓN', 28, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Scoponi, Liliana Marcela', ''],
  ['Dirección de Empresas', 'EP00418', 'START UPS Y CORPORATE ENTREPRENEURSHIP', 29, '0- NO INICIADO', '', ''],
  ['Dirección de Empresas', 'PLAN-30', 'SIMULACIÓN ESTRATÉGICA Y GESTIÓN DE EQUIPOS', 30, '', '', ''],
  ['Dirección de Empresas', 'PLAN-31', 'TRABAJO FINAL', 31, '', '', ''],

  ['Nuevas Tecnologías', 'EP01898', 'ESTRATEGIA EXPONENCIAL', 1, '5.FINALIZADA', 'Gisela Veritier e Inés Anciola', 'Lucía Rodriguez'],
  ['Nuevas Tecnologías', 'EP00459', 'FINANZAS Y CONTABILIDAD PARA LA TECNOLOGÍA', 2, '5.FINALIZADA', 'Lucas Matias Elettore', 'Evelin Pineda'],
  ['Nuevas Tecnologías', 'EP01487', 'LIDERAZGO DIGITAL Y TOMA DE DECISIONES', 3, '5.FINALIZADA', 'Carlos Luis Spontón', 'Evelin Pineda'],
  ['Nuevas Tecnologías', 'EP00614', 'DERECHO ESTRATÉGICO', 4, '5.FINALIZADA', 'Juan Sebastián Querro', 'Evelin Pineda'],
  ['Nuevas Tecnologías', 'EP00461', 'TALLERES DE APOYO PARA LA REALIZACIÓN DEL TRABAJO FINAL', 5, 'Requiere ajuste y revisión', 'Ricardo Medel', 'Evelin Pineda'],
  ['Nuevas Tecnologías', 'EP01850', 'APRENDIZAJE AUTOMÁTICO E INTELIGENCIA ARTIFICIAL PARA LÍDERES TECNOLÓGICOS/AS', 6, '5.FINALIZADA', '', ''],
  ['Nuevas Tecnologías', 'EP01455', 'LA TECNOLOGÍA Y EL DERECHO', 7, '5.FINALIZADA', 'Juan Sebastián Querro', 'Evelin Pineda'],
  ['Nuevas Tecnologías', 'EP00688', 'GESTIÓN DE OPERACIONES EN TI', 8, '5.FINALIZADA', 'Ignacio Casanovas', 'Evelin Pineda'],
  ['Nuevas Tecnologías', 'EP01869', 'SUSTENTABILIDAD Y ODS', 9, '2.CONSTRUCCIÓN DE CONTENIDOS', '', ''],
  ['Nuevas Tecnologías', 'PLAN-10', 'ÉTICA, CUMPLIMIENTO CORPORATIVO Y PERSPECTIVA IGNACIANA', 10, '', '', ''],
  ['Nuevas Tecnologías', 'EP02040', 'SEMINARIO I: GESTIÓN DE PRODUCTOS Y SERVICIOS', 11, '3.MAQUETACIÓN', 'Sandra Aronica', 'Victoria Coria'],
  ['Nuevas Tecnologías', 'EP01026', 'SEMINARIO II: ADQUISICIÓN DE INVERSIONES', 12, '5.FINALIZADA', 'Maira Calzada', 'Victoria Coria'],
  ['Nuevas Tecnologías', 'EP01158', 'SEMINARIO III', 13, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Luciano Crisafulli', 'Victoria Coria'],
  ['Nuevas Tecnologías', 'EP02069', 'AGILIDAD Y TRANSFORMACIÓN ORGANIZACIONAL', 14, '3.MAQUETACIÓN', '', ''],
  ['Nuevas Tecnologías', 'EP02033', 'RECURSOS HUMANOS Y ANALÍTICA DE DATOS', 15, '5.FINALIZADA', '', ''],
  ['Nuevas Tecnologías', 'EP00720', 'CREACIÓN DE VALOR EN LA ECONOMÍA DE LA EXPERIENCIA', 16, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Yéssica Sepúlveda', 'Yamile Abed'],
  ['Nuevas Tecnologías', 'EP01051', 'COMPORTAMIENTO ORGANIZACIONAL EN LA GESTIÓN DE LA TECNOLOGÍA', 17, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Ignacio Casanovas', 'Yamile Abed'],
  ['Nuevas Tecnologías', 'EP02043', 'DIRECCIÓN DE PROYECTOS INTEGRADOS', 18, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Adriana Pérez', 'Victoria Coria'],
  ['Nuevas Tecnologías', 'EP01007', 'EL MARKETING DE LA EXPERIENCIA DE CLIENTES (CX)', 19, '', '', ''],
  ['Nuevas Tecnologías', 'EP00031', 'INNOVACIÓN ABIERTA', 20, '2.CONSTRUCCIÓN DE CONTENIDOS', '', ''],
  ['Nuevas Tecnologías', 'PLAN-21', 'CADENAS GLOBALES DE VALOR Y NUEVAS INDUSTRIAS', 21, '', '', ''],
  ['Nuevas Tecnologías', 'EP02197', 'EL CAMINO DE LOS UNICORNIOS', 22, '', '', ''],
  ['Nuevas Tecnologías', 'EP01662', 'CAPITAL DE RIESGO CORPORATIVO', 23, '1.CONTRATACIÓN', '', ''],
  ['Nuevas Tecnologías', 'EP01282', 'DESARROLLO Y COMPETITIVIDAD', 24, '0. PROXIMAMENTE', '', ''],
  ['Nuevas Tecnologías', 'EP00121', 'LEGISLACIÓN EN TECNOLOGÍAS Y PROPIEDAD INTELECTUAL', 25, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Pusiol, Dante Andrés', 'Julieta Santo'],
  ['Nuevas Tecnologías', 'EP01676', 'ESTRATEGIA DE CIBERSEGURIDAD Y RESPUESTA EJECUTIVA', 26, '0. PROXIMAMENTE', '', ''],
  ['Nuevas Tecnologías', 'EP00750', 'SEGURIDAD DE LA INFORMACIÓN EMPRESARIAL', 27, '', '', ''],
  ['Nuevas Tecnologías', 'EP00783', 'ARQUITECTURA MODERNA DE BASE DE DATOS', 28, '0. PROXIMAMENTE', '', ''],
  ['Nuevas Tecnologías', 'EP00622', 'CADENA DE BLOQUES', 29, '', '', ''],
  ['Nuevas Tecnologías', 'EP01392', 'INTELIGENCIA ARTIFICIAL APLICADA I', 30, '5. (OM) FINALIZADA', '', ''],
  ['Nuevas Tecnologías', 'EP02194', 'ANALÍTICA Y MINERÍA DE DATOS', 31, '', '', ''],
  ['Nuevas Tecnologías', 'EP00411', 'CONFIGURACIONES, PROCESOS Y TECNOLOGÍAS', 32, '0. PROXIMAMENTE', '', ''],
  ['Nuevas Tecnologías', 'EP02079', 'INTELIGENCIA ARTIFICIAL APLICADA II', 33, '', '', ''],
  ['Nuevas Tecnologías', 'EP00337', 'CIBER DELITO', 34, '', '', ''],
  ['Nuevas Tecnologías', 'PLAN-35', 'REINGENIERÍA Y CICLO DE VIDA DE DESARROLLO DE SISTEMAS', 35, '', '', ''],
  ['Nuevas Tecnologías', 'PLAN-36', 'INTRODUCCIÓN A LAS FINANZAS TECNOLÓGICAS', 36, '', '', ''],
  ['Nuevas Tecnologías', 'PLAN-37', 'INTRODUCCIÓN A LOS SEGUROS TECNOLÓGICOS', 37, '', '', ''],
  ['Nuevas Tecnologías', 'PLAN-38', 'FINANZAS DIGITALES Y FINANZAS ALTERNATIVAS', 38, '', '', ''],
  ['Nuevas Tecnologías', 'PLAN-39', 'MARCOS REGULATORIOS DE LAS FINANZAS TECNOLÓGICAS', 39, '', '', ''],
  ['Nuevas Tecnologías', 'PLAN-40', 'MARCOS REGULATORIOS DE LOS SEGUROS TECNOLÓGICOS', 40, '', '', ''],
  ['Nuevas Tecnologías', 'PLAN-41', 'INTERNET DE LAS COSAS APLICADO AL ECOSISTEMA', 41, '', '', ''],
  ['Nuevas Tecnologías', 'PLAN-42', 'INTELIGENCIA ARTIFICIAL APLICADA I (electiva)', 42, '', '', ''],
  ['Nuevas Tecnologías', 'PLAN-43', 'CADENA DE BLOQUES APLICADA', 43, '', '', ''],
  ['Nuevas Tecnologías', 'PLAN-44', 'COMERCIALIZACIÓN DIGITAL', 44, '', '', ''],
  ['Nuevas Tecnologías', 'PLAN-45', 'INTELIGENCIA ARTIFICIAL APLICADA II (electiva)', 45, '', '', ''],
  ['Nuevas Tecnologías', 'EP00827', 'TRABAJO FINAL', 46, '', '', ''],

  ['Dirección y Liderazgo', 'EP01505', 'LA ESTRATEGIA Y EL FACTOR HUMANO', 1, '5.FINALIZADA', '', ''],
  ['Dirección y Liderazgo', 'EP00512', 'LOS RECURSOS HUMANOS EN LA ERA DIGITAL', 2, '5.FINALIZADA', '', ''],
  ['Dirección y Liderazgo', 'EP01295', 'LA CULTURA ORGANIZACIONAL', 3, '5.FINALIZADA', '', ''],
  ['Dirección y Liderazgo', 'EP00566', 'LIDERAZGO DE EQUIPOS DE TRABAJO Y DE LA TRANSFORMACIÓN', 4, '5.FINALIZADA', '', ''],
  ['Dirección y Liderazgo', 'EP02125', 'COMPETENCIAS, INNOVACIÓN Y MODELOS DE NEGOCIOS', 5, '5.FINALIZADA', '', ''],
  ['Dirección y Liderazgo', 'EP02103', 'RECURSOS HUMANOS Y ANALÍTICA DE DATOS I', 6, '5.FINALIZADA', '', ''],
  ['Dirección y Liderazgo', 'EP00461', 'TALLERES DE APOYO PARA LA REALIZACIÓN DEL TRABAJO FINAL', 7, '5.FINALIZADA', '', ''],
  ['Dirección y Liderazgo', 'EP00177', 'ATRACCIÓN, SELECCIÓN Y RETENCIÓN DE TALENTOS', 8, '2.CONSTRUCCIÓN DE CONTENIDOS', '', ''],
  ['Dirección y Liderazgo', 'EP02069', 'AGILIDAD Y TRANSFORMACIÓN ORGANIZACIONAL', 9, '3.MAQUETACIÓN', '', ''],
  ['Dirección y Liderazgo', 'EP00022', 'GESTIÓN DE LA EXPERIENCIA DE EMPLEADOS/AS (EX)', 10, '5.FINALIZADA', '', ''],
  ['Dirección y Liderazgo', 'EP01007', 'EL MARKETING DE LA EXPERIENCIA DE CLIENTES (CX)', 11, '5.FINALIZADA', 'Cristian Balmaceda', ''],
  ['Dirección y Liderazgo', 'EP01282', 'DESARROLLO Y COMPETITIVIDAD', 12, '3.MAQUETACIÓN', 'Elisa Panero', 'Lucía Moro'],
  ['Dirección y Liderazgo', 'EP01849', 'DESEMPEÑO Y RENDIMIENTO', 13, '3.MAQUETACIÓN', 'Scaramuzza, María Laura', ''],
  ['Dirección y Liderazgo', 'EP00504', 'NEUROCIENCIA APLICADA A LAS ORGANIZACIONES I', 14, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Roldán González de las Cuevas, Luis', 'Evelin Pineda'],
  ['Dirección y Liderazgo', 'EP01131', 'LAS RELACIONES LABORALES', 15, '', '', ''],
  ['Dirección y Liderazgo', 'EP01130', 'RECURSOS HUMANOS Y ANALÍTICA DE DATOS II', 16, '2.CONSTRUCCIÓN DE CONTENIDOS', '', ''],
  ['Dirección y Liderazgo', 'EP00562', 'HERRAMIENTAS PARA POTENCIAR EL DESARROLLO Y EL LIDERAZGO', 17, '5.FINALIZADA', 'Juan José Bauducco', ''],
  ['Dirección y Liderazgo', 'EP00429', 'CAMBIO Y NUEVA MENTALIDAD', 18, '2.CONSTRUCCIÓN DE CONTENIDOS', '', ''],
  ['Dirección y Liderazgo', 'EP00756', 'SEMINARIO I', 19, '', '', ''],
  ['Dirección y Liderazgo', 'EP01100', 'NEUROCIENCIA APLICADA A LAS ORGANIZACIONES II', 20, '2.CONSTRUCCIÓN DE CONTENIDOS', '', ''],
  ['Dirección y Liderazgo', 'EP01756', 'ESTRATEGIA REMUNERATIVA', 21, '3.MAQUETACIÓN', 'Hernán Stucky y Mariana Petelin', ''],
  ['Dirección y Liderazgo', 'EP00200', 'MEDICIÓN INTEGRADA DE LA GESTIÓN DE LAS PERSONAS', 22, '', '', ''],
  ['Dirección y Liderazgo', 'EP00356', 'ÉTICA, CUMPLIMIENTO CORPORATIVO Y PERSPECTIVA IGNACIANA', 23, 'CONTRATO S/A', '', ''],
  ['Dirección y Liderazgo', 'EP01869', 'SUSTENTABILIDAD Y ODS', 24, '5.FINALIZADA', '', ''],
  ['Dirección y Liderazgo', 'EP01314', 'SEMINARIO II', 25, '', '', ''],
  ['Dirección y Liderazgo', 'EP00211', 'TRABAJO FINAL', 26, '', '', ''],

  ['Dirección Estratégica de Proyectos', 'EP02931', 'FUNDAMENTOS DE LA GESTIÓN DE PROYECTOS', 1, '5.FINALIZADA', 'Laura Conti', 'Agostina Cortona'],
  ['Dirección Estratégica de Proyectos', 'EP02932', 'ANÁLISIS Y VIABILIDAD DE PROYECTOS', 2, '3.MAQUETACIÓN', 'Carlos Aire', 'Sebastian Rodriguez'],
  ['Dirección Estratégica de Proyectos', 'EP01869', 'SUSTENTABILIDAD Y ODS', 3, '5.FINALIZADA', 'Marybel Alvarez Gatti', 'Agostina Cortona'],
  ['Dirección Estratégica de Proyectos', 'EP02934', 'IDEACIÓN DE SOLUCIONES', 4, '3.MAQUETACIÓN', 'Fernando Frías', 'Julieta Santo'],
  ['Dirección Estratégica de Proyectos', 'EP02935', 'PLANIFICACIÓN Y GESTIÓN DE LAS ENTREGAS', 5, '3.MAQUETACIÓN', 'Gonzalo Andrés Mozas', 'Julieta Santo'],
  ['Dirección Estratégica de Proyectos', 'EP02936', 'GESTIÓN DE LA CALIDAD', 6, '1. CONTRATO S/A', 'Emiliano Marino', 'Julieta Santo'],
  ['Dirección Estratégica de Proyectos', 'EP02937', 'EL DESEMPEÑO DEL PROYECTO', 7, '3.MAQUETACIÓN', 'Carolina Ciccioli', 'Sebastian Rodriguez'],
  ['Dirección Estratégica de Proyectos', 'EP02938', 'GESTIÓN DEL RIESGO Y LA INCERTIDUMBRE', 8, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Angel Martinez', ''],
  ['Dirección Estratégica de Proyectos', 'EP00461', 'TALLERES DE APOYO PARA LA REALIZACIÓN DEL TRABAJO FINAL', 9, '0. PROXIMAMENTE', '', ''],
  ['Dirección Estratégica de Proyectos', 'EP02940', 'GESTIÓN DE LOS INTERESADOS Y LAS COMUNICACIONES', 10, '1. CONTRATO S/A', '', ''],
  ['Dirección Estratégica de Proyectos', 'EP02941', 'COMPRAS Y CONTRATOS DEL PROYECTO', 11, '3.MAQUETACIÓN', 'Adrian Dolgonos', 'Yamile Abed'],
  ['Dirección Estratégica de Proyectos', 'EP02942', 'SEMINARIO I', 12, '', '', ''],
  ['Dirección Estratégica de Proyectos', 'EP02943', 'EL EQUIPO DEL PROYECTO', 13, '5.FINALIZADA', 'Elisa Panero', 'Agostina Cortona'],
  ['Dirección Estratégica de Proyectos', 'EP00728', 'HABILIDADES Y COMPETENCIAS DIRECTIVAS', 14, '2.CONSTRUCCIÓN DE CONTENIDOS', '', ''],
  ['Dirección Estratégica de Proyectos', 'EP02109', 'LIDERAZGO INSPIRADOR Y CREADOR DE VALOR', 15, '5.FINALIZADA', '', ''],
  ['Dirección Estratégica de Proyectos', 'EP02946', 'AGILE PROJECT MANAGEMENT', 16, '3.MAQUETACIÓN', 'Belén Zarazaga', 'Sebastian Rodriguez'],
  ['Dirección Estratégica de Proyectos', 'EP02947', 'ORGANIZACIONES ÁGILES', 17, '', '', ''],
  ['Dirección Estratégica de Proyectos', 'EP02948', 'SEMINARIO II', 18, '', '', ''],
  ['Dirección Estratégica de Proyectos', 'EP02949', 'DIRECCIÓN Y GESTIÓN DE PROGRAMAS Y PORTAFOLIOS', 19, '', '', ''],
  ['Dirección Estratégica de Proyectos', 'EP02950', 'NORMAS Y MODELOS PARA LA GESTIÓN DE PROYECTOS', 20, '', 'Laura Conti', ''],
  ['Dirección Estratégica de Proyectos', 'EP02951', 'GESTIÓN DE PROYECTOS PÚBLICOS Y SOCIALES', 21, '', 'Paola Niela', ''],
  ['Dirección Estratégica de Proyectos', 'EP02952', 'FINANZAS PARA LA GESTIÓN DE PROYECTOS', 22, '', 'Martin Bertoni', ''],
  ['Dirección Estratégica de Proyectos', 'EP00356', 'ÉTICA, CUMPLIMIENTO CORPORATIVO Y PERSPECTIVA IGNACIANA', 23, '5.FINALIZADA', '', ''],
  ['Dirección Estratégica de Proyectos', 'EP02954', 'SEMINARIO III', 24, '0. PROXIMAMENTE', '', ''],
  ['Dirección Estratégica de Proyectos', 'EP02955', 'TRABAJO FINAL', 25, '', '', ''],

  ['Innovación de Negocios', 'EP01850', 'APRENDIZAJE AUTOMÁTICO E INTELIGENCIA ARTIFICIAL PARA LÍDERES TECNOLÓGICOS/AS', 1, '5.FINALIZADA', '', ''],
  ['Innovación de Negocios', 'EP00882', 'NUEVAS FRONTERAS DE CONOCIMIENTO', 2, '', '', ''],
  ['Innovación de Negocios', 'EP02253', 'NEUROCIENCIAS Y CREATIVIDAD I', 3, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Néstor Gasso', 'Julieta Santo'],
  ['Innovación de Negocios', 'EP01392', 'INTELIGENCIA ARTIFICIAL APLICADA I', 4, '5.FINALIZADA', 'Virgolini Pablo Alejandro', 'Anahí Azcuy'],
  ['Innovación de Negocios', 'EP01869', 'SUSTENTABILIDAD Y ODS', 5, '5.FINALIZADA', '', ''],
  ['Innovación de Negocios', 'EP02079', 'INTELIGENCIA ARTIFICIAL APLICADA II', 6, '2.CONSTRUCCIÓN DE CONTENIDOS', '', ''],
  ['Innovación de Negocios', 'EP00031', 'INNOVACIÓN ABIERTA', 7, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Nicolas Novaira', 'Adriana Hermosilla'],
  ['Innovación de Negocios', 'EP02069', 'AGILIDAD Y TRANSFORMACIÓN ORGANIZACIONAL', 8, '2.CONSTRUCCIÓN DE CONTENIDOS', '', ''],
  ['Innovación de Negocios', 'EP01818', 'CREATIVIDAD II Y PROGRAMAS DE INNOVACIÓN', 9, '', '', ''],
  ['Innovación de Negocios', 'EP00461', 'TALLERES DE APOYO PARA LA REALIZACIÓN DEL TRABAJO FINAL', 10, '', '', ''],
  ['Innovación de Negocios', 'EP01781', 'MINDFULLNESS EN EMPRESAS Y ORGANIZACIONES', 11, '', '', ''],
  ['Innovación de Negocios', 'EP00356', 'ÉTICA, CUMPLIMIENTO CORPORATIVO Y PERSPECTIVA IGNACIANA', 12, '5.FINALIZADA', '', ''],
  ['Innovación de Negocios', 'EP02033', 'RECURSOS HUMANOS Y ANALÍTICA DE DATOS', 13, '5.FINALIZADA', '', ''],
  ['Innovación de Negocios', 'EP01406', 'EMPRENDEDORISMO DISCIPLINADO', 14, '', '', ''],
  ['Innovación de Negocios', 'EP00571', 'TEORÍA DE RESOLUCIÓN DE PROBLEMAS DE INVENTIVA TRIZ', 15, '', '', ''],
  ['Innovación de Negocios', 'EP01898', 'ESTRATEGIA EXPONENCIAL', 16, '5.FINALIZADA', '', ''],
  ['Innovación de Negocios', 'EP00459', 'FINANZAS Y CONTABILIDAD PARA LA TECNOLOGÍA', 17, '5.FINALIZADA', '', ''],
  ['Innovación de Negocios', 'EP01487', 'LIDERAZGO DIGITAL Y TOMA DE DECISIONES', 18, '5.FINALIZADA', '', ''],
  ['Innovación de Negocios', 'EP00324', 'SEMINARIO', 19, '', '', ''],
  ['Innovación de Negocios', 'EP01007', 'EL MARKETING DE LA EXPERIENCIA DE CLIENTES (CX)', 20, '2.CONSTRUCCIÓN DE CONTENIDOS', '', ''],
  ['Innovación de Negocios', 'EP02197', 'EL CAMINO DE LOS UNICORNIOS', 21, '', '', ''],
  ['Innovación de Negocios', 'EP01690', 'FINANZAS DIGITALES Y FINANZAS ALTERNATIVAS', 22, '', '', ''],
  ['Innovación de Negocios', 'EP02017', 'TRABAJO FINAL', 23, '', '', ''],

  ['Operaciones y Cadena de Valor', 'EP02591', 'INTRODUCCIÓN A LA CADENA DE VALOR', 1, '3.MAQUETACIÓN', '', ''],
  ['Operaciones y Cadena de Valor', 'EP01233', 'SISTEMAS DE INFORMACIÓN', 2, '8.DUPLICAR (NCC)', '', ''],
  ['Operaciones y Cadena de Valor', 'EP01277', 'DIRECCIÓN DE OPERACIONES', 3, '6.REVISIÓN Y AJUSTE', 'Nicolás Gabarro', 'Adriana Hermosilla'],
  ['Operaciones y Cadena de Valor', 'EP00878', 'REFLEXIÓN Y ANÁLISIS ESTRATÉGICO', 4, '5.FINALIZADA', '', ''],
  ['Operaciones y Cadena de Valor', 'EP02531', 'HERRAMIENTAS MATEMÁTICAS Y CONTABLES', 5, '3.MAQUETACIÓN', 'Valentina Pulcina', 'Victoria Coria'],
  ['Operaciones y Cadena de Valor', 'EP02335', 'HIGIENE Y SEGURIDAD', 6, '2.CONSTRUCCIÓN DE CONTENIDOS', 'Lucas Javier Pavón Piscitello', 'Victoria Coria'],
  ['Operaciones y Cadena de Valor', 'EP00461', 'TALLERES DE APOYO PARA LA REALIZACIÓN DEL TRABAJO FINAL', 7, '0. NO INICIADA', '', ''],
  ['Operaciones y Cadena de Valor', 'EP00402', 'ANÁLISIS FINANCIERO PARA LA TOMA DE DECISIONES', 8, '5. (OM) FINALIZADA', '', ''],
  ['Operaciones y Cadena de Valor', 'EP01514', 'DIRECCIÓN DEL TRANSPORTE', 9, '0. CONTRATO S/A', '', ''],
  ['Operaciones y Cadena de Valor', 'EP01500', 'GESTIÓN DE PROYECTOS', 10, '1.CONTRATACIÓN', '', ''],
  ['Operaciones y Cadena de Valor', 'EP00139', 'LIDERAZGO INSPIRADOR Y GESTIÓN DEL TALENTO', 11, '2.CONSTRUCCIÓN DE CONTENIDOS', '', ''],
  ['Operaciones y Cadena de Valor', 'EP02044', 'SATISFACTORES Y CANALES: EL MARKETING DE LA EXPERIENCIA DEL CLIENTE', 12, '5. (OM) FINALIZADA', '', ''],
  ['Operaciones y Cadena de Valor', 'EP00209', 'GESTIÓN PRESUPUESTARIA Y DEL CAPITAL DE TRABAJO', 13, '5. (OM) FINALIZADA', '', ''],
  ['Operaciones y Cadena de Valor', 'EP01183', 'LOGÍSTICA COMERCIAL Y PLANEAMIENTO DE LA DEMANDA', 14, '0. NO INICIADA', '', ''],
  ['Operaciones y Cadena de Valor', 'EP01470', 'ENTORNO JURÍDICO DE LA ACTIVIDAD', 15, '5. (OM) FINALIZADA', '', ''],
  ['Operaciones y Cadena de Valor', 'EP00966', 'ESTRATEGIAS Y DECISIONES', 16, '8.DUPLICAR (NCC)', '', ''],
  ['Operaciones y Cadena de Valor', 'EP02486', 'DIRECCIÓN DE DISTRIBUCIÓN', 17, '0. NO INICIADA', '', ''],
  ['Operaciones y Cadena de Valor', 'EP02442', 'LOGÍSTICA INTERNACIONAL', 18, '0. NO INICIADA', '', ''],
  ['Operaciones y Cadena de Valor', 'EP02191', 'ADMINISTRACIÓN DE CENTROS DE DISTRIBUCIÓN', 19, '0. NO INICIADA', '', ''],
  ['Operaciones y Cadena de Valor', 'EP01778', 'LOGÍSTICA 4.0 WORLD CLASS LOGISTIC', 20, '0. NO INICIADA', '', ''],
  ['Operaciones y Cadena de Valor', 'EP01864', 'SEMINARIO I', 21, '0. NO INICIADA', '', ''],
  ['Operaciones y Cadena de Valor', 'EP02560', 'LOGÍSTICA DE COMPRAS Y ABASTECIMIENTO', 22, '0. NO INICIADA', '', ''],
  ['Operaciones y Cadena de Valor', 'EP00235', 'INNOVACIÓN EN MODELOS DE NEGOCIOS', 23, '2.CONSTRUCCIÓN DE CONTENIDOS', '', ''],
  ['Operaciones y Cadena de Valor', 'EP01740', 'CONTROL INTEGRADO DE LA GESTIÓN', 24, '0. (OM) PROXIMAMENTE', '', ''],
  ['Operaciones y Cadena de Valor', 'EP01025', 'ÉTICA, RESPONSABILIDAD SOCIAL EMPRESARIA Y SUSTENTABILIDAD', 25, '0. (OM) PROXIMAMENTE', '', ''],
  ['Operaciones y Cadena de Valor', 'EP02114', 'SEMINARIO II', 26, '0. NO INICIADA', '', ''],
  ['Operaciones y Cadena de Valor', 'PLAN-27', 'TRABAJO FINAL', 27, '', '', ''],
]
